### ISSUE TITLE
Problème lors de la récupération de données en REST

### ISSUE THREAD

**Issue by Quentin61** [Quentin61/Springboot-tds#3]
Bonjour, 

Normalement, lorsque j'essaie de récupérer tous les scripts ou un script, je devrais obtenir une ou plusieurs lignes avec les données correspondantes.

Mais lorsque j'essaie de récupérer les données dans le navigateur avec l'URL par une méthode Get j'obtiens une erreur stackOverflow et il affiche mes données en boucle. 

fonctions que j'essaye d'executer : 
```java
    @GetMapping("/rest/script/{id}")
    public Script read(@PathVariable String id)
    {
        return this.scriptRepository.getOne(Integer.parseInt(id));
    } 
```
@jcheron

**Comment by jcheron** [comment]
Vous chargez les Scripts,
Chaque Script a des historics
Chaque Historic a des Scripts
et chaque Script...
Ce qui provoque la stackOverflow 
https://github.com/Quentin61/Springboot-tds/blob/949cb23345b9b0acbcaf6211c9a864a2baeb7e6b/src/main/java/s4/spring/td5/entities/Script.java#L31

Enlever le Cascade Type.ALL côté histo
https://github.com/Quentin61/Springboot-tds/blob/949cb23345b9b0acbcaf6211c9a864a2baeb7e6b/src/main/java/s4/spring/td5/entities/History.java#L13

et mettez: 
```java
@ManyToOne(cascade = {CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH})
```
Ca devrait être suffisant.

**Comment by Quentin61** [comment]
J'ai le même problème qui persiste

**Comment by jcheron** [comment]
Regardez à partir de Script ce qui pourrait partir en boucle, comme autre entité,
sinon essayez aussi en mettant `CascadeType.NONE`

**Comment by Quentin61** [comment]
Le correcteur ne connait pas NONE, j'ai ces propositions :
![image](https://user-images.githubusercontent.com/45429939/77772009-be8b2380-7047-11ea-9b38-4a616f2fc2fd.png)

**Comment by jcheron** [comment]
oui, il suffit d'enlever le `cascade`

**Comment by Quentin61** [comment]
Est ce que vous auriez les imports liés à Type.NONE ? je n'arrive pas à les trouver @jcheron

**Comment by jcheron** [comment]
Vous n'avez pas vu mon message du dessus, il suffit d'enlever le `cascade`
```java
@OneToMany
private List<History>...
```
