### ISSUE TITLE
Passer des argument avec la méthode http avec un controller rest

### ISSUE THREAD

**Issue by Quentin61** [Quentin61/Springboot-tds#4]
Bonjour,

J'essaye d'appeler une méthode d'un controller rest (qui a plusieurs argument `@RequestParam`) avec la fonction :
```java
http.get("urlRest',...);
```
Mais je ne sais pas comment passer plusieurs paramètres.  
@jcheron

**Comment by jcheron** [comment]
Les request params sont les variables passées dans l'url:
`/test?id=5&search=bob`
Dans ce cas, il serait préférable de faire un post
`Http.post("url",(Object)("json string"),"code récupérant response.data");`

**Comment by Quentin61** [comment]
si on fait passer un objet qui contient deux Strings, comment on les récupères du coté de la méthode du contrôler rest ?

**Comment by jcheron** [comment]
Vous créez une classe SearchObject dont le ou les membres correspondent aux paramètres envoyés, et vous l'utilisez pour récupérer ke requestBody:
```
	@PostMapping("/test")
	public ArrayList<Script> getScripts(@RequestBody SearchObject searchO) {
        }
```
