### ISSUE TITLE
Problème lors de la récupération des scripts avec un response.data

### ISSUE THREAD

**Issue by Quentin61** [Quentin61/Springboot-tds#5]
Bonjour, 

J'essaye de récupérer les scripts dans une méthode ```Http.post(...)```. Les scripts que je récupèrent sont mis dans un variable qui est ```self.scripts``` (self est un variable local qui contient this).

Lorsque j'affiche mes scripts, j'obtiens un tableau avec la liste de mes scripts.

Cependant j'obtiens aussi des erreurs java scripts qui m'indiquent que dans le template, l'objet que j'affiche est un string et pas un tableau. j'ai notamment cette erreur : ```vue.js:634 [Vue warn]: Invalid prop: type check failed for prop "items". Expected Array, got String with value "scripts".```

Je crains aussi que cette erreur empêche d'afficher les objets à l'intérieur de mes scripts.

Je récupère mes scripts de cette manière :
```java
vueJS.addMethod("searchBy","let self=this;"+Http.post(restUrl,(Object)"{'search': this.search, 'type': this.type}","self.scripts = response.data;"));
```

et je les mets dans la vue de cette manière :

```java
vueJS.addData("scripts",(Object)"scripts");
```
 @jcheron

**Comment by jcheron** [comment]
Et que retourne votre `restUrl`, quand vous y allez directement ?

**Comment by Quentin61** [comment]
Ma méthode rest retourne une liste de scripts

**Comment by jcheron** [comment]
Vous pouvez mettre la base de données sur le repo, merci.

Sinon, ça c'est inutile:
```java
vueJS.addData("scripts",(Object)"scripts");
```
Il serait préférable de charger tous les scripts par défaut...

**Comment by Quentin61** [comment]
j'ai ajouté une ligne qui ajoute par défaut tous les scripts : ```vueJS.addData("scripts",this.scriptRepository.findAll());```

Maintenant je n'ai plus d'erreur. En revanche je ne sais pas comment accéder à la variable d'un objet dans un script.  J'ai actuellement dans mon template pour afficher les champs ceci : 
```html
<td><?scripts.name?></td>
<td class="text-xs-right"><? scripts.category.name ?></td>
<td class="text-xs-right"><? scripts.language.name ?></td> 
```
mais lors de l'affichage, il m'affiche pour le nom de catégorie et du langage que c'est un objet.
@jcheron

**Comment by jcheron** [comment]
Il faut les parcourir les scripts, c'est un array...
```html
<ul>
  <li v-for="script in scripts" :key="script.id">
    <? script.name ?>
  </li>
</ul>
```

**Comment by Quentin61** [comment]
J'utilise un tableau pour afficher les scripts , et il me met une erreur quand j'utilise un v-for dans un template. j'utilise : ```html
                <v-data-table
                        :headers="headers"
                        :items="scripts"
                        class="elevation-1">
                    <template v-slot:items="scripts">
                        <td><%scripts.name?></td>
                        <td class="text-xs-right"><% scripts.category.name %></td>
                        <td class="text-xs-right"><% scripts.language.name %></td>
                    </template>
                </v-data-table>
```
et j'obtiens ceci : 

![image](https://user-images.githubusercontent.com/45429939/78036354-78490380-736a-11ea-8d67-c6ebff222201.png)
@jcheron

**Comment by jcheron** [comment]
Chaque script est accessible par `scripts.item`
```
                    <template v-slot:items="scripts">
                        <td><%scripts.item.name?></td>
                        <td class="text-xs-right"><% scripts.item.category.name %></td>
                        <td class="text-xs-right"><% scripts.item.language.name %></td>
                    </template>
```
