### ISSUE TITLE
problème de lancement application heroku 

### ISSUE THREAD

**Issue by Quentin61** [Quentin61/Springboot-tds#7]
Bonjour,
 
Lorsque j'essaye de lancer mon application à partir de heroku, mais j'obtiens cette erreur :

![image](https://user-images.githubusercontent.com/45429939/78450909-6c1eb800-7682-11ea-86db-a00c1c83cdcc.png)

j'ai téléchargé le client pour voir les détails des log et j'ai obtenu deux codes d'erreurs :

![image](https://user-images.githubusercontent.com/45429939/78451028-1bf42580-7683-11ea-83af-ba0cdfcf8a4b.png)

mais je ne sais pas comment les régler. @jcheron

**Comment by jcheron** [comment]
Bonjour,
Ca dit qu'aucun service web n'est démarré...
Il faut que votre projet Spring soit à la racine de la branche, et pas dans un sous-dossier,
et que sous Heroku, le buildpack java soit ajouté à l'application (logiquement c'est automatique).

**Comment by Quentin61** [comment]
Le problème venait du type de package, il fallait changer le .war en .jar dans le fichier pom.xml
